name: dataoutai
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - bokeh~=2.4.2
  - python~=3.7.12
  - matplotlib
  - networkx~=2.6.3
  - notebook
  - numpy
  - gensim
  - pandas~=1.1.5
  - requests~=2.23.0
  - scikit-learn~=1.0.1
  - scipy
  - seaborn~=0.11.2
  - sentence-transformers~=2.1.0
  - pip
  - pyvis~=0.1.9
  - pydantic~=1.8.2
  - pytorch=1.10.1
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - cudatoolkit=11.3
  - pip:
    - black