name: dataoutai
channels:
  - conda-forge
  - defaults
dependencies:
  - python~=3.7.12
  - matplotlib
  - notebook
  - numpy
  - gensim
  - pandas~=1.1.5
  - requests~=2.23.0
  - scikit-learn~=1.0.1
  - scipy
  - seaborn~=0.11.2
  - pip
  - pip:
    - black